### ISSUE TITLE
Add CI to repo

### ISSUE THREAD

**Issue by radu-matei** [radu-matei/vsts-brigade-gateway#2]

**Comment by cscheib** [comment]
I could potentially work on this after the work I did on #5 is merged.  Is there a target CI system?  GitHub Actions? Azure DevOps Pipelines?  CircleCI?

**Comment by radu-matei** [comment]
Hi, and thanks a lot for help so far!

For projects in the `brigadecore` organization we have a Brigade instance that we use for CI (as well as for dogfooding Brigade) - so we can ask @vdice to create a Brigade project for us, then we can add a `brigade.js` file that uses our utils library (https://github.com/brigadecore/brigade-utils).

**Comment by vdice** [comment]
A [Brigade project](https://brigadecore.github.io/kashti/projects/brigade-c484e36ca1446cbd850dae845c575b48cad4fe871e49309acce03a) for this repo has been created.  Ready for a `brigade.js` file to be added!

**Comment by krancour** [comment]
Closing due to staleness, but please do reopen if necessary.
